version: "3"

services:
  nginx:
    build: ./bin/nginx
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    links:
      - php
    depends_on:
      - php
    networks:
      - main_network
  php:
    build:
      context: bin/php/${PHP_VERSION}
      args:
        uname: ${UNAME-php}
        uid: ${UID-1000}
        gid: ${UID-1000}
    container_name: ${PROJECT_NAME}_php
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www/html
      - ./config/php/${PHP_VERSION}/php.ini:/usr/local/etc/php/php.ini
      - composer:/var/www/.composer/cache
    links:
      - db
      - elasticsearch
    depends_on:
      - db
      - mailer
    environment:
      COMPOSER_MEMORY_LIMIT: -1
      XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
      PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
    networks:
      - main_network
  db:
    build: ./bin/mariadb
    container_name: ${PROJECT_NAME}_mariadb
    restart: 'always'
    ports:
      - "3306:3306"
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./logs/mariadb:/var/log/mysql
      - ./config/mariadb/conf.d:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0 --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: db
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    networks:
      - main_network
  mailer:
      image: mailhog/mailhog
      container_name: ${PROJECT_NAME}_mailer
      ports:
          - "8082:8025"
          - "1025:1025"
      networks:
        - main_network
  elasticsearch:
    build: ./bin/elasticsearch/${ELASTICSEARCH_VERSION}
    container_name: ${PROJECT_NAME}_es
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=2gb
      - cluster.routing.allocation.disk.watermark.high=1gb
      - cluster.routing.allocation.disk.watermark.flood_stage=512mb
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/elasticsearch/${ELASTICSEARCH_VERSION}:/usr/share/elasticsearch/data
      - ./logs/elasticsearch/${ELASTICSEARCH_VERSION}:/usr/share/elasticsearch/logs
    ports:
      - "9200:9200"
    networks:
      - main_network
volumes:
  composer:
networks:
  main_network:
    driver: bridge
    name: ${PROJECT_NAME}_main_network
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET_IP}/${SUBNET_MASK}
